var questions = 8;
var questionsLeft = ' [' + questions + ' questions left]';
var noun = prompt('Please type a noun' + questionsLeft);
questions -= 1;
var verb = prompt('Please type a verb' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions + ' questions left]';
var adjective = prompt('Please type an adjective ' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions + ' questions left]';
var noun2 = prompt('Please type a noun' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions + ' questions left]';
var verb2 = prompt('Please type a verb in past tense' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions + ' questions left]';
var condiment =  prompt('Please type in a condiment' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions + ' questions left]';
var complaint = prompt('Please type in a restaurant complaint:' + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions + ' questions left]';
var tantrum = prompt("Please fill the blank in the past tense: _________ the ball to me." + questionsLeft);
questions -= 1;
questionsLeft = ' [' + questions + ' questions left]';


alert('All done. Ready for the message?');
var sentence = " There once was a " + noun;
sentence += ' who wanted to ' + verb;
sentence += ' the ' + adjective;
sentence += ' restaurant. One day the ' + noun2;
sentence += ' ' + verb2;
sentence += ' in and demanded for ' + condiment;
sentence += ' the ' + noun;
sentence += ' said, NO! ' + complaint;
sentence += ' the ' + noun2;
sentence += ' did not like that response and ' + tantrum;
sentence += ' a tantrum. The ' + noun;
sentence += ' said, "Get out of my restaurant!"';
document.write(sentence);